---
title: "Example Application"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example Application}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bslib)
library(shiny)
library(shiny.destroy)
```

```{r, eval = FALSE}
boxModuleUI <- function(id) {
  ns <- NS(id)

  bslib::card(
    id = ns("card"),
    actionButton(ns("destroy"), "Remove card")
  )
}

boxModuleServer <- function(id) {
  moduleServer(id, function(input, output, session) {
    observeEvent(input$destroy, destroyModule())
  })
}

destroyableBoxModuleUI <- makeModuleUIDestroyable(boxModuleUI)
destroyableBoxModuleServer <- makeModuleServerDestroyable(boxModuleServer)

ui <- bslib::page_fluid(
  h1("Destroyable Modules"),
  p("Number of boxes:", textOutput("n_modules", inline = TRUE)),
  actionButton("create", "Create new module"),
  bslib::layout_columns(id = "cards")
)

server <- function(input, output, session) {
  card_id <- reactiveVal(1L)

  observeEvent(input$create, {
    ns_id <- paste0("card_", card_id())

    insertUI("#cards", "beforeEnd", destroyableBoxModuleUI(id = ns_id))
    destroyableBoxModuleServer(id = ns_id)

    card_id(card_id() + 1L)
  })

  output$n_modules <- renderText({
    sum(grepl("destroy", names(input)))
  })
}

shinyApp(ui, server)
```
